const ACTION_TYPE = {
  LOGIN_ACTION : "LOGIN_ACTION",
  SIGNUP_ACTION : "SIGNUP_ACTION",
  VIEW_ENTRIES : "VIEW_ENTRIES",
  NEW_ENTRY:"NEW_ENTRY",
  VIEW_ONE_ENTRY:"VIEW_ONE_ENTRY",
  DELETE_ONE_ENTRY:"DELETE_ONE_ENTRY",
  MODIFY_ENTRY:"MODIFY_ENTRY"
};
export default ACTION_TYPE;
